version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "store_db"
      POSTGRES_USER: "store_user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database_init:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
